version: "3.9"

services:
  postgres:
    image: postgres:16
    container_name: todo_postgres
    restart: always
    environment:
      POSTGRES_USER: todo_app
      POSTGRES_PASSWORD: 0MMD65ZnSy5/N49I
      POSTGRES_DB: todo
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

  api:
    build: .
    restart: always
    ports:
      - "8080:8080"
    env_file:
      - .env
    depends_on:
      - postgres
    healthcheck:
      test: ["CMD", "wget", "-qO-", "http://localhost:8080/health"]
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
